# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 206e9bc46d8891dc6473a8f3645e1e66812d92dbd5d8b152f84a7d606be45f1b30f6989c3677db8ecdf38cd0ade82c35309389f61f527e716dda829f9f06ed67

test:
  secret_key_base: eadb551eae30b51d87efbf3456960f91cc88d3fd8c53cef5fa898ca60b3015d3bebfdbf790d7b7e9096c2a5fb2c3021b8d4c4afa5f286660e16eebbc7ecb0c76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
